"""Seeded synthetic option chain generated BY Black-Scholes.

Samples option-contract parameters ``(S, K, T, r, q, sigma)`` over realistic grids
(moneyness around ATM, a term structure of expiries, plausible rates/dividends and
a vol level) and labels each contract with its exact Black-Scholes PRICE using the
hand-rolled kernel in :mod:`nnvsbs.pricing.black_scholes`. All randomness is drawn
from a seeded :func:`nnvsbs._rng.make_rng` generator, so a given seed reproduces a
byte-identical chain.

HONEST FRAMING: because the labels ARE Black-Scholes prices, a neural net fit to
this chain can at best RECOVER the Black-Scholes surface (a sanity / convergence
check, not an improvement — beating the data-generating process is impossible). The
genuine smile-mispricing finding lives on REAL chains (:mod:`nnvsbs.data.chains`).

``numpy`` is a hard dependency; ``pandas`` (the ``[data]`` extra) is imported
lazily inside the generator. Importing this module has no side effects.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any, Literal

import numpy as np

from nnvsbs._exceptions import InsufficientDataError, ValidationError
from nnvsbs._rng import make_rng

if TYPE_CHECKING:  # pragma: no cover - typing only
    import pandas as pd

#: The discrete quote dates the synthetic grid is stamped with so the leakage-free
#: group-by-quote-date split has well-defined groups. A modest count of dates keeps
#: the train/test folds non-trivial while every contract on a given date shares the
#: same underlying spot (the near-duplicate structure the group split defends).
_N_QUOTE_DATES: int = 5

#: Columns, in order, of the synthetic / real option panel produced here.
#: ``price`` is the Black-Scholes label on synthetic data (the market mid on real
#: chains). ``quote_date`` groups contracts quoted on the same day for the
#: leakage-free split.
CHAIN_COLUMNS: tuple[str, ...] = (
    "quote_date",
    "S",
    "K",
    "T",
    "r",
    "q",
    "sigma",
    "kind",
    "price",
)


@dataclass(frozen=True, slots=True)
class SyntheticChain:
    """A seeded synthetic option chain plus the config that produced it.

    Attributes
    ----------
    frame:
        The option panel: one row per contract, columns :data:`CHAIN_COLUMNS`.
    n_quotes:
        The number of contracts in :attr:`frame`.
    seed:
        The master RNG seed used to draw the grid.
    spot:
        The single underlying spot the grid was sampled around.
    vol:
        The single constant volatility used to label every contract (the
        constant-vol assumption the smile study later stress-tests).
    data_source:
        Always ``"synthetic"`` for this generator.
    """

    frame: pd.DataFrame
    n_quotes: int
    seed: int
    spot: float
    vol: float
    data_source: str = "synthetic"
    extra: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-safe ``dict`` of the chain *metadata* (not the frame)."""
        return {
            "n_quotes": int(self.n_quotes),
            "seed": int(self.seed),
            "spot": float(self.spot),
            "vol": float(self.vol),
            "data_source": str(self.data_source),
            "extra": dict(self.extra),
        }


def generate_synthetic_chain(
    *,
    n_quotes: int = 500,
    spot: float = 100.0,
    vol: float = 0.20,
    r: float = 0.03,
    q: float = 0.0,
    moneyness_range: tuple[float, float] = (0.8, 1.2),
    expiry_range: tuple[float, float] = (7.0 / 365.0, 2.0),
    rights: Literal["call", "put", "both"] = "call",
    seed: int = 7,
) -> SyntheticChain:
    """Generate a seeded synthetic option chain labeled with Black-Scholes prices.

    Draws ``n_quotes`` contracts by sampling moneyness ``K/S`` uniformly over
    ``moneyness_range`` and time-to-expiry over ``expiry_range`` (with a small set
    of discrete quote dates so the leakage-free group split has groups), then prices
    each with the hand-rolled Black-Scholes kernel at the single constant ``vol``.

    Parameters
    ----------
    n_quotes:
        Number of contracts to sample (default ``500``).
    spot:
        The underlying spot price the grid is centered on (default ``100.0``).
    vol:
        The single constant volatility used to label every contract (default
        ``0.20``). This is the constant-vol assumption the smile study probes.
    r, q:
        Risk-free rate and continuous dividend yield (defaults ``0.03`` / ``0.0``).
    moneyness_range:
        Inclusive ``(low, high)`` bounds on ``K/S`` (default ``(0.8, 1.2)``).
    expiry_range:
        Inclusive ``(low, high)`` bounds on ``T`` in years (default ``7d``-``2y``).
    rights:
        Which option right(s) to sample: ``"call"`` (default, the learnable shipped
        surface), ``"put"``, or ``"both"`` (alternating, for parity exercises). With
        ``"both"`` the BS price is no longer a pure function of the leakage-free
        features (``kind`` is intentionally excluded), so the NN cannot fully recover
        it — the default is a single right.
    seed:
        Master RNG seed (default ``7``).

    Returns
    -------
    SyntheticChain
        The frozen chain wrapper around the labeled panel.

    Raises
    ------
    ValidationError
        If ``n_quotes`` is non-positive, ``spot``/``vol`` is non-positive, ``r``/``q``
        is non-finite, or a range bound is degenerate/inverted.
    InsufficientDataError
        If ``n_quotes`` is fewer than the number of discrete quote dates (so each
        quote-date group would otherwise be empty).
    """
    import pandas as pd

    from nnvsbs.pricing.black_scholes import bs_price

    _validate_grid(
        n_quotes=n_quotes,
        spot=spot,
        vol=vol,
        r=r,
        q=q,
        moneyness_range=moneyness_range,
        expiry_range=expiry_range,
    )

    rng = make_rng(seed)

    # Sample contract geometry. Moneyness ``K/S`` and time-to-expiry ``T`` are drawn
    # uniformly over their realistic ranges; strikes follow from the single spot.
    moneyness = rng.uniform(moneyness_range[0], moneyness_range[1], size=n_quotes)
    strikes = spot * moneyness
    expiries = rng.uniform(expiry_range[0], expiry_range[1], size=n_quotes)

    # Assign the option right(s). The DEFAULT is calls-only: because the NN feature
    # set (moneyness, T, r, q, realized_vol) deliberately omits ``kind`` to avoid any
    # circular input, a single right keeps the BS PRICE a deterministic function of
    # the features, so the NN can RECOVER the surface (the sanity check). ``"both"``
    # alternates calls/puts to exercise parity downstream, but then price is no longer
    # a pure function of the leakage-free features.
    if rights == "both":
        kinds = np.where(rng.uniform(size=n_quotes) < 0.5, "call", "put")
    else:
        kinds = np.full(n_quotes, rights, dtype=object).astype(str)

    # Stamp each contract with one of a small set of discrete quote dates so the
    # leakage-free group split has groups. Dates are assigned round-robin over a
    # business-day index, keeping every group non-empty for ``n_quotes`` >= dates.
    quote_dates_index = pd.bdate_range("2026-01-05", periods=_N_QUOTE_DATES)
    quote_date_pos = np.arange(n_quotes) % _N_QUOTE_DATES
    quote_dates = quote_dates_index[quote_date_pos]

    spot_arr = np.full(n_quotes, spot, dtype="float64")
    r_arr = np.full(n_quotes, r, dtype="float64")
    q_arr = np.full(n_quotes, q, dtype="float64")
    sigma_arr = np.full(n_quotes, vol, dtype="float64")

    # Label every contract with its EXACT Black-Scholes price via the project's
    # single hand-rolled kernel — the NN target is therefore BS-generated, so the
    # NN can at best RECOVER this surface (a sanity check, not an edge). Calls and
    # puts are priced in their own vectorized batches because ``kind`` is scalar.
    prices = np.empty(n_quotes, dtype="float64")
    for kind in ("call", "put"):
        mask = kinds == kind
        if not bool(mask.any()):
            continue
        prices[mask] = np.asarray(
            bs_price(
                spot_arr[mask],
                strikes[mask],
                expiries[mask],
                r_arr[mask],
                q_arr[mask],
                sigma_arr[mask],
                kind=kind,
            ),
            dtype="float64",
        )

    frame = pd.DataFrame(
        {
            "quote_date": quote_dates,
            "S": spot_arr,
            "K": strikes,
            "T": expiries,
            "r": r_arr,
            "q": q_arr,
            "sigma": sigma_arr,
            "kind": kinds,
            "price": prices,
        }
    )[list(CHAIN_COLUMNS)]

    return SyntheticChain(
        frame=frame,
        n_quotes=n_quotes,
        seed=seed,
        spot=spot,
        vol=vol,
    )


def _validate_grid(
    *,
    n_quotes: int,
    spot: float,
    vol: float,
    r: float,
    q: float,
    moneyness_range: tuple[float, float],
    expiry_range: tuple[float, float],
) -> None:
    """Validate the synthetic-grid parameters before any sampling.

    Parameters
    ----------
    n_quotes:
        Requested contract count.
    spot, vol:
        Underlying spot and the single constant volatility (both strictly positive).
    r, q:
        Risk-free rate and dividend yield (finite).
    moneyness_range, expiry_range:
        Inclusive ``(low, high)`` bounds; ``low`` must be positive and strictly less
        than ``high``.

    Raises
    ------
    ValidationError
        If any scalar is non-positive/non-finite or a range bound is inverted.
    InsufficientDataError
        If ``n_quotes`` is fewer than the discrete quote-date count.
    """
    if spot <= 0.0 or not np.isfinite(spot):
        raise ValidationError(f"spot must be positive and finite, got {spot}.")
    if vol <= 0.0 or not np.isfinite(vol):
        raise ValidationError(f"vol must be positive and finite, got {vol}.")
    if not np.isfinite(r):
        raise ValidationError(f"r must be finite, got {r}.")
    if not np.isfinite(q):
        raise ValidationError(f"q must be finite, got {q}.")
    _validate_range(moneyness_range, name="moneyness_range", require_positive_low=True)
    _validate_range(expiry_range, name="expiry_range", require_positive_low=True)
    if n_quotes <= 0:
        raise ValidationError(f"n_quotes must be positive, got {n_quotes}.")
    if n_quotes < _N_QUOTE_DATES:
        raise InsufficientDataError(
            f"n_quotes must be at least {_N_QUOTE_DATES} (one per quote date), got {n_quotes}."
        )


def _validate_range(bounds: tuple[float, float], *, name: str, require_positive_low: bool) -> None:
    """Validate an inclusive ``(low, high)`` range bound.

    Parameters
    ----------
    bounds:
        The ``(low, high)`` pair.
    name:
        Human-readable label for error messages.
    require_positive_low:
        When ``True`` the low bound must be strictly positive (strikes/expiries).

    Raises
    ------
    ValidationError
        If the bounds are non-finite, inverted, or violate the positivity rule.
    """
    low, high = bounds
    if not (np.isfinite(low) and np.isfinite(high)):
        raise ValidationError(f"{name} bounds must be finite, got {bounds}.")
    if require_positive_low and low <= 0.0:
        raise ValidationError(f"{name} low bound must be positive, got {low}.")
    if not low < high:
        raise ValidationError(f"{name} must satisfy low < high, got {bounds}.")
