"""Options: NN vs Black-Scholes — wraps the vendored ``nnvsbs`` library.

Endpoint:
  POST /tools/nn-vs-bs/run — price European options two ways (a hand-rolled
  Black-Scholes closed form vs a small neural net served from a committed ONNX
  artifact) and compare them HONESTLY on out-of-sample REPRICE error only.

HONEST FRAMING (the nuance — never an overclaim):
  * On SYNTHETIC data generated BY Black-Scholes, the NN can at best RECOVER the
    BS surface (target reprice RMSE ~1e-2 of price). That is a SANITY / CONVERGENCE
    check, NEVER an "improvement" — beating the data-generating process is
    impossible. The shipped default (``mode="synthetic"``) shows BS ≈ NN with the
    explicit caption that this is a convergence check, not an edge.
  * The only genuine finding is on REAL chains: BS with a single constant vol
    systematically MISPRICES the volatility smile/skew (Dumas-Fleming-Whaley 1998),
    and a non-circular NN can lower out-of-sample reprice error across moneyness.
  * The reported metrics are reprice RMSE / MAE + a Diebold-Mariano test on the
    paired error series. There is deliberately NO Sharpe / DSR / P&L anywhere — no
    strategy exists here, so any such statistic would be fabricated.

LEAKAGE GUARDS (all enforced INSIDE the vendored library):
  * implied vol is a BS inversion of the target price, so it NEVER enters the NN
    feature vector (``assert_no_leakage``); IV is an analysis OUTPUT only;
  * real chains are split by QUOTE DATE (group split, test strictly future of
    train) — never a random split over near-duplicate adjacent strikes/expiries;
  * the StandardScaler inside the model Pipeline is fit on the TRAIN fold ONLY.

SERVE PATH — onnxruntime ONLY, NEVER torch. The shipped model is a tiny (<50KB)
ONNX MLP trained OFFLINE on synthetic BS data and committed inside the vendored
package (``artifacts/nn_vs_bs_mlp.onnx``). This router imports NO torch; inference
runs through onnxruntime. The honest convergence result is reproducible without a
GPU and without any market-data key.

DATA REALITY: there is no option-chain API key in this environment, so the request
default is ``data_source_pref='synthetic'`` (a seeded Black-Scholes grid). The
``mode="real"`` yfinance path is available when live chains can be fetched.

Robustness:
  - The ONNX session is loaded LAZILY at module level (``_SESSION = None``) on the
    first request; a missing / unreadable artifact surfaces as a 502.
  - Best-effort row in ``platform.tool_runs`` for run accounting; failures are
    logged but never propagate to the client.
"""

from __future__ import annotations

import json
import logging
import math
import threading
from typing import Any, Literal

import plotly.io as pio
from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel, Field, field_validator, model_validator

from ..deps import get_supabase

# Importing the vendor package side-effects ``sys.path`` so that ``import nnvsbs``
# resolves to the vendored copy. This MUST run before the ``from nnvsbs import ...``
# below, so the import block is hand-ordered and isort is suppressed (matching the
# live hrp-portfolio / lstm-forecast convention).
from ..lib import nn_vs_bs as _vendor_marker  # noqa: F401

from nnvsbs import (  # import resolves via the sys.path shim above
    ArtifactError,
    InsufficientDataError,
    LeakageError,
    ValidationError,
    default_artifact_path,
    run_nn_vs_bs,
)

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/tools/nn-vs-bs", tags=["nn-vs-bs"])


# ---------------------------------------------------------------------------
# Lazy onnxruntime session (serve path; loaded on first call, NEVER imports torch)
# ---------------------------------------------------------------------------

#: The shared onnxruntime ``InferenceSession`` for the committed artifact. Typed
#: loosely (``object``) so importing this module never imports onnxruntime. It is
#: created lazily on the first request via :func:`_get_session`.
_SESSION: object | None = None
_SESSION_LOCK = threading.Lock()


def _get_session() -> object:
    """Return the process-wide onnxruntime session, loading it lazily once.

    onnxruntime is imported INSIDE this function — importing the router module
    never pulls in an inference engine, and torch is never imported on this path.
    A missing / unreadable artifact raises :class:`ArtifactError`, which the
    endpoint maps to a 502.
    """
    global _SESSION
    if _SESSION is not None:
        return _SESSION
    with _SESSION_LOCK:
        if _SESSION is not None:  # pragma: no cover - double-checked locking
            return _SESSION
        artifact_path = default_artifact_path()
        if not artifact_path.is_file():
            raise ArtifactError(f"nn-vs-bs ONNX artifact not found at {artifact_path}.")
        import onnxruntime as ort

        _SESSION = ort.InferenceSession(
            str(artifact_path),
            providers=["CPUExecutionProvider"],
        )
        logger.info("nn-vs-bs onnxruntime session initialized from %s", artifact_path)
        return _SESSION


# ---------------------------------------------------------------------------
# Pydantic models
# ---------------------------------------------------------------------------

CompareMode = Literal["synthetic", "real"]
DataSourcePref = Literal["auto", "synthetic"]
DataSource = Literal["synthetic", "yfinance"]


class ContractSpec(BaseModel):
    """An optional single explicit European contract to price alongside the grid."""

    S: float = Field(..., gt=0.0, description="Spot price of the underlying (> 0).")
    K: float = Field(..., gt=0.0, description="Strike price (> 0).")
    T: float = Field(..., gt=0.0, le=10.0, description="Time to expiry in years (0 < T <= 10).")
    r: float = Field(0.0, ge=-0.5, le=1.0, description="Risk-free rate (continuous).")
    q: float = Field(0.0, ge=-0.5, le=1.0, description="Dividend yield (continuous).")


class NnVsBsRequest(BaseModel):
    """Wire contract for a nn-vs-bs compare run.

    The shipped model serves via onnxruntime against a committed synthetic-BS-trained
    ONNX MLP. There is no option-chain key in this environment, so the default
    ``data_source_pref`` is ``'synthetic'`` (a seeded Black-Scholes grid on which the
    NN can only RECOVER the BS surface — the honest convergence check).
    """

    mode: CompareMode = Field(
        "synthetic",
        description="synthetic (seeded BS grid; default) | real (yfinance chain).",
    )
    ticker: str = Field("SPY", description="Underlying symbol (used when mode='real').")
    contract: ContractSpec | None = Field(
        default=None,
        description="Optional explicit single contract {S,K,T,r,q} to price alongside the grid.",
    )
    n_quotes: int = Field(
        500,
        ge=50,
        le=5_000,
        description="Synthetic grid size for mode='synthetic' (default 500).",
    )
    data_source_pref: DataSourcePref = Field(
        "synthetic",
        description="auto | synthetic. No chain key here, so 'synthetic' is the default path.",
    )
    seed: int = Field(7, ge=0, le=999_999, description="Master seed (deterministic synthetic grid).")

    @field_validator("ticker")
    @classmethod
    def _normalise_ticker(cls, v: str) -> str:
        cleaned = v.strip().upper()
        if not cleaned:
            raise ValueError("ticker must be a non-empty string")
        return cleaned

    @model_validator(mode="after")
    def _real_needs_ticker(self) -> NnVsBsRequest:
        if self.mode == "real" and not self.ticker:
            raise ValueError("ticker is required when mode='real'")
        return self


class NnVsBsResponse(BaseModel):
    summary: dict[str, Any] = Field(
        ...,
        description=(
            "Scalar summary: bs_rmse, nn_rmse, mae_bs, mae_nn, dm_stat, dm_pvalue, "
            "nn_recovers_bs (bool), n_quotes, data_source. (nn_recovers_bs is a PURE "
            "function of the inference — on synthetic BS data it reads TRUE when the "
            "NN recovers the BS surface within the sanity band; it is a convergence "
            "check, NEVER a tradable-edge claim. No Sharpe / P&L is ever reported.)"
        ),
    )
    smile_figure: dict[str, Any] = Field(
        ..., description="Plotly figure JSON: price vs moneyness — BS vs NN vs (real) market."
    )
    error_by_moneyness_figure: dict[str, Any] = Field(
        ..., description="Plotly figure JSON: reprice error sliced by moneyness — BS vs NN."
    )
    data_source: DataSource


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _safe_float(value: float | None) -> float | None:
    if value is None:
        return None
    try:
        f = float(value)
    except (TypeError, ValueError):
        return None
    if math.isnan(f) or math.isinf(f):
        return None
    return f


def _figure_json(fig: Any) -> dict[str, Any]:
    """Normalise a library figure into a plain ``{data, layout}`` JSON dict.

    The vendored figure builders already return plain JSON-serializable
    ``{data, layout}`` mappings, but we round-trip through ``pio.to_json``
    defensively so any stray numpy scalar / Timestamp is coerced exactly like the
    hrp-portfolio / lstm-forecast tools do.
    """
    payload: dict[str, Any] = json.loads(pio.to_json(fig, validate=False))
    return payload


def _empty_figure(title: str) -> dict[str, Any]:
    import plotly.graph_objects as go

    fig = go.Figure()
    fig.update_layout(title=title, height=360)
    payload: dict[str, Any] = json.loads(pio.to_json(fig, validate=False))
    return payload


# ---------------------------------------------------------------------------
# Endpoint
# ---------------------------------------------------------------------------


@router.post("/run", response_model=NnVsBsResponse)
def run(
    req: NnVsBsRequest,
    supabase=Depends(get_supabase),
) -> NnVsBsResponse:
    """Execute the nn-vs-bs compare pipeline (single-shot, sync).

    Pipeline (all inside the vendored library; serve via onnxruntime, NO torch):
      build a seeded synthetic BS grid (or load a real yfinance chain) → build the
      non-circular feature matrix (IV NEVER enters) + the leakage-free quote-date
      group split → price every contract two ways (hand-rolled Black-Scholes vs the
      committed ONNX MLP) → out-of-sample reprice RMSE/MAE overall and by moneyness
      → Diebold-Mariano on the paired errors → the honest ``nn_recovers_bs`` verdict
      → the smile and error-by-moneyness Plotly figures. NO Sharpe / P&L anywhere.
    """
    # Eagerly warm the lazy onnxruntime session so a missing/unreadable artifact
    # surfaces as a clean 502 before we run the (cheap) compare.
    try:
        _get_session()
    except ArtifactError as exc:
        logger.exception("nn-vs-bs ONNX artifact load failed")
        _maybe_log_failure(supabase, req, exc)
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=f"NN-vs-BS artifact load failed: {exc.__class__.__name__}: {exc}",
        ) from exc
    except Exception as exc:  # noqa: BLE001 — normalize any onnxruntime init error to 502
        logger.exception("nn-vs-bs onnxruntime session init failed")
        _maybe_log_failure(supabase, req, exc)
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=f"NN-vs-BS session init failed: {exc.__class__.__name__}: {exc}",
        ) from exc

    params: dict[str, Any] = {
        "ticker": req.ticker,
        "n_quotes": int(req.n_quotes),
    }
    if req.contract is not None:
        params["contract"] = req.contract.model_dump()

    try:
        result = run_nn_vs_bs(mode=req.mode, params=params, seed=int(req.seed))
    except (InsufficientDataError, LeakageError, ValidationError) as exc:
        logger.warning("nn-vs-bs run rejected: %s", exc)
        _maybe_log_failure(supabase, req, exc)
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=f"NN-vs-BS run rejected: {exc.__class__.__name__}: {exc}",
        ) from exc
    except ArtifactError as exc:
        logger.exception("nn-vs-bs artifact error during run")
        _maybe_log_failure(supabase, req, exc)
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=f"NN-vs-BS artifact error: {exc.__class__.__name__}: {exc}",
        ) from exc
    except Exception as exc:
        logger.exception("nn-vs-bs run failed")
        _maybe_log_failure(supabase, req, exc)
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=f"NN-vs-BS run failed: {exc.__class__.__name__}: {exc}",
        ) from exc

    raw = result.summary
    # ``nn_recovers_bs`` is a pure, structurally-constrained boolean from the library;
    # the router NEVER recomputes or overrides it. NO Sharpe / P&L field exists.
    summary: dict[str, Any] = {
        "bs_rmse": _safe_float(raw.bs_rmse),
        "nn_rmse": _safe_float(raw.nn_rmse),
        "mae_bs": _safe_float(raw.mae_bs),
        "mae_nn": _safe_float(raw.mae_nn),
        "dm_stat": _safe_float(raw.dm_stat),
        "dm_pvalue": _safe_float(raw.dm_pvalue),
        "nn_recovers_bs": bool(raw.nn_recovers_bs),
        "n_quotes": int(raw.n_quotes),
        "data_source": str(raw.data_source),
        "verdict": str(raw.verdict),
        "rationale": str(raw.rationale),
    }

    # --- Figures (best-effort; never fatal) ---------------------------------
    try:
        smile_json = _figure_json(result.smile_figure)
    except Exception:
        logger.exception("nn-vs-bs smile figure failed (non-fatal)")
        smile_json = _empty_figure("Option price vs moneyness: BS vs NN")
    try:
        error_json = _figure_json(result.error_by_moneyness_figure)
    except Exception:
        logger.exception("nn-vs-bs error-by-moneyness figure failed (non-fatal)")
        error_json = _empty_figure("Reprice error by moneyness: BS vs NN")

    data_source = str(raw.data_source)
    response = NnVsBsResponse(
        summary=summary,
        smile_figure=smile_json,
        error_by_moneyness_figure=error_json,
        data_source=data_source,  # type: ignore[arg-type]
    )

    _maybe_log_run(supabase, req, response)
    return response


# ---------------------------------------------------------------------------
# Supabase helpers (best-effort)
# ---------------------------------------------------------------------------


def _maybe_log_run(supabase, req: NnVsBsRequest, resp: NnVsBsResponse) -> None:
    if supabase is None:
        return
    try:
        supabase.schema("platform").table("tool_runs").insert(
            {
                "tool_slug": "nn-vs-bs",
                "params": req.model_dump(mode="json"),
                "result": {
                    "data_source": resp.data_source,
                    "summary": resp.summary,
                },
                "status": "ok",
            }
        ).execute()
    except Exception:
        logger.exception("tool_runs insert failed (non-fatal)")


def _maybe_log_failure(supabase, req: NnVsBsRequest, exc: BaseException) -> None:
    if supabase is None:
        return
    try:
        supabase.schema("platform").table("tool_runs").insert(
            {
                "tool_slug": "nn-vs-bs",
                "params": req.model_dump(mode="json"),
                "result": None,
                "status": "error",
                "error": f"{exc.__class__.__name__}: {exc}",
            }
        ).execute()
    except Exception:
        logger.exception("tool_runs failure insert failed (non-fatal)")
