"""nn-vs-bs — Options pricing: a small neural net vs Black-Scholes, compared honestly.

A from-scratch Black-Scholes-Merton pricer (price + Greeks + an implied-vol solver)
benchmarked against a small ``scikit-learn`` MLP (exported to ONNX via ``skl2onnx``
and served by ``onnxruntime`` — NO torch). The comparison is REPRICE error only.

HONEST FRAMING (the whole point):

- On SYNTHETIC data generated BY Black-Scholes, the NN can at best RECOVER the BS
  surface (reprice RMSE within a sanity band) — a convergence/sanity check, NEVER
  an improvement, because beating the data-generating process is impossible.
- The genuine finding is on REAL chains: constant-vol Black-Scholes systematically
  misprices the volatility smile (Dumas-Fleming-Whaley 1998), and a non-circular NN
  can lower out-of-sample reprice error across moneyness.
- The reported metrics are out-of-sample reprice RMSE/MAE and a Diebold-Mariano
  test. There is NO tradable P&L / Sharpe / DSR — no strategy exists, so any such
  statistic would be fabricated.

LEAKAGE GUARDS (enforced + property-tested): implied vol is a Black-Scholes
inversion of the target price and is therefore NEVER a NN feature; real chains are
split by QUOTE DATE with an embargo (no future-in-train); the ``StandardScaler`` is
fit on the TRAIN fold only.

IMPORT PURITY: this package has ZERO import-time side effects and imports NO
torch / onnx / skl2onnx / onnxruntime / scikit-learn at module load — those live
behind lazy imports inside the training and serve functions. ``python -c "import
nnvsbs"`` succeeds with only the base (numpy) dependency present.

Public API is curated below; see :data:`__all__`.
"""

from __future__ import annotations

from nnvsbs._constants import EPS, PERIODS_PER_YEAR, TRADING_DAYS
from nnvsbs._exceptions import (
    ArtifactError,
    ConvergenceError,
    InsufficientDataError,
    LeakageError,
    NnVsBsError,
    ValidationError,
)
from nnvsbs._manifest import RunManifest, config_hash
from nnvsbs._rng import make_rng, spawn_substreams
from nnvsbs._validation import (
    align_inner,
    ensure_dataframe,
    ensure_series,
    validate_min_obs,
)
from nnvsbs.data.chains import load_option_chain
from nnvsbs.data.synthetic import (
    CHAIN_COLUMNS,
    SyntheticChain,
    generate_synthetic_chain,
)
from nnvsbs.evaluation.dm import DieboldMarianoResult, diebold_mariano
from nnvsbs.evaluation.reprice import (
    RepriceErrors,
    reprice_errors,
    reprice_errors_by_moneyness,
)
from nnvsbs.evaluation.verdict import (
    RepriceVerdict,
    RepriceVerdictResult,
    derive_verdict,
)
from nnvsbs.features.build import (
    FEATURE_COLUMNS,
    FORBIDDEN_FEATURE_COLUMNS,
    assert_no_leakage,
    build_features,
    quote_date_group_split,
)
from nnvsbs.models.mlp import (
    MLPConfig,
    build_mlp_pipeline,
    export_pipeline_to_onnx,
)
from nnvsbs.models.onnx_runtime import OnnxPricer, default_artifact_path
from nnvsbs.plots import error_by_moneyness_figure, smile_figure
from nnvsbs.pricing.black_scholes import (
    BlackScholesGreeks,
    bs_delta,
    bs_gamma,
    bs_price,
    bs_rho,
    bs_theta,
    bs_vega,
)
from nnvsbs.pricing.iv import implied_volatility
from nnvsbs.serve import CompareRun, CompareSummary, run_compare, run_nn_vs_bs
from nnvsbs.train import TrainResult, train_synthetic_mlp

__version__ = "0.1.0"

# Curated public API. Sorted (ruff RUF022) rather than grouped; the import block
# above is organized by subpackage for readers who want the logical grouping.
__all__ = [
    "CHAIN_COLUMNS",
    "EPS",
    "FEATURE_COLUMNS",
    "FORBIDDEN_FEATURE_COLUMNS",
    "PERIODS_PER_YEAR",
    "TRADING_DAYS",
    "ArtifactError",
    "BlackScholesGreeks",
    "CompareRun",
    "CompareSummary",
    "ConvergenceError",
    "DieboldMarianoResult",
    "InsufficientDataError",
    "LeakageError",
    "MLPConfig",
    "NnVsBsError",
    "OnnxPricer",
    "RepriceErrors",
    "RepriceVerdict",
    "RepriceVerdictResult",
    "RunManifest",
    "SyntheticChain",
    "TrainResult",
    "ValidationError",
    "__version__",
    "align_inner",
    "assert_no_leakage",
    "bs_delta",
    "bs_gamma",
    "bs_price",
    "bs_rho",
    "bs_theta",
    "bs_vega",
    "build_features",
    "build_mlp_pipeline",
    "config_hash",
    "default_artifact_path",
    "derive_verdict",
    "diebold_mariano",
    "ensure_dataframe",
    "ensure_series",
    "error_by_moneyness_figure",
    "export_pipeline_to_onnx",
    "generate_synthetic_chain",
    "implied_volatility",
    "load_option_chain",
    "make_rng",
    "quote_date_group_split",
    "reprice_errors",
    "reprice_errors_by_moneyness",
    "run_compare",
    "run_nn_vs_bs",
    "smile_figure",
    "spawn_substreams",
    "train_synthetic_mlp",
    "validate_min_obs",
]
